### ISSUE TITLE
Board not rebooting after flashing image

### ISSUE THREAD

**Issue by damien-lemoal** [vowstar/kflash.py#2]
Hi there !

My MAIX bit board does not reboot automatically anymore after flashing an image. I get:

```
 kflash -p /dev/ttyUSB0 -b 1500000 -t output/images/u-boot.bin
[INFO] COM Port Selected Manually:  /dev/ttyUSB0 
[INFO] Default baudrate is 115200 , later it may be changed to the value you set. 
[INFO] Trying to Enter the ISP Mode... 
._
[INFO] Automatically detected goE/kd233 

[INFO] Greeting Message Detected, Start Downloading ISP 
Downloading ISP: |=================================================================| 100.0% 10kiB/s
[INFO] Booting From 0x80000000 
[INFO] Wait For 0.1 second for ISP to Boot 
[INFO] Boot to Flashmode Successfully 
[INFO] Selected Baudrate:  1500000 
[INFO] Baudrate changed, greeting with ISP again ...  
[INFO] Boot to Flashmode Successfully 
[INFO] Selected Flash:  On-Board 
[INFO] Initialization flash Successfully 
Programming BIN: |=================================================================| 100.0% 50kiB/s
[INFO] Rebooting... 
--- forcing DTR inactive
--- forcing RTS inactive
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
```
and then nothing... I always need to hit the board reset button to get it to boot into the new image.
Any idea what is going on ?

**Comment by vowstar** [comment]
I guess it is related to DTR and RTS controll logic from kflash or ch552. Can you provide a photo of your MAIX bit board? Let me identify which serial chip it uses, ch552 or ch340? (This problem is also solvable, the worst case may have to update the firmware of the ch552, the best case is to modify kflash to solve)

**Comment by damien-lemoal** [comment]
The chip on my board says CH552T. Just tried the latest 1.1.1 and still no automatic reboot. It used to work well with the older sipeed kflash.py code.

**Comment by damien-lemoal** [comment]
Note: I did not do a full bisect, but if I revert back to v 1.0.3 (commit 696c578d9c3ad84f1f36e9ce2e79875583a08b78), then the board does reboot after flashing. going back to v1.0.5, no reboot. It looks like patch acef7ef1db398506a9ed05898ee990fb986cc480 "kflash.py: fix erase logic and progressbar" is the one breaking things. From this patch on, no reboot.

**Comment by vowstar** [comment]
Thanks for the info, these are helpful, I'm debugging this issue.

**Comment by damien-lemoal** [comment]
Great. Thanks. Let me know when you have something and I will test !

**Comment by vowstar** [comment]
This problem may have been fixed in https://github.com/vowstar/kflash.py/releases/tag/v1.1.2, please give it a try.

**Comment by damien-lemoal** [comment]
Just tried. The board is rebooting, but keeps rebooting... With my buildroot setup booting into u-boot, I get this:

```
./kflash.py -b 1500000 -t -p /dev/ttyUSB0 ../../buildroot/output/images/u-boot.bin
[INFO] COM Port Selected Manually:  /dev/ttyUSB0 
[INFO] Default baudrate is 115200 , later it may be changed to the value you set. 
[INFO] Trying to Enter the ISP Mode... 
._
[INFO] Automatically detected goE/kd233/bit_mic 

[INFO] Greeting Message Detected, Start Downloading ISP 
Downloading ISP: |=====================================================================================| 100.0% 10kiB/s
[INFO] Booting From 0x80000000 
[INFO] Wait For 0.1 second for ISP to Boot 
[INFO] Boot to Flashmode Successfully 
[INFO] Selected Baudrate:  1500000 
[INFO] Baudrate changed, greeting with ISP again ...  
[INFO] Boot to Flashmode Successfully 
[INFO] Selected Flash:  On-Board 
[INFO] Initialization flash Successfully 
Programming BIN: |=====================================================================================| 100.0% 50kiB/s
[INFO] Rebooting... 
[INFO] The ISP stub tells us the k210 is rebooting ... 
--- forcing DTR inactive
--- forcing RTS inactive
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---


U-Boot 2022.04 (May 27 2022 - 10:25:08 +0900)

DRAM:  8 MiB
Core:  34 devices, 17 uclasses, devicetree: separate


U-Boot 2022.04 (May 27 2022 - 10:25:08 +0900)

DRAM:  8 MiB
Core:  34 devices, 17 uclasses, devicetree: separate


U-Boot 2022.04 (May 27 2022 - 10:25:08 +0900)

DRAM:  8 MiB
Core:  34 devices, 17 uclasses, devicetree: separate


U-Boot 2022.04 (May 27 2022 - 10:25:08 +0900)

DRAM:  8 MiB
Core:  34 devices, 17 uclasses, devicetree: separate
...
```
And on. It does not stop.

**Comment by damien-lemoal** [comment]
Note: please do not tag a new version for every patch you add. Let's test first before tagging a new version :)

**Comment by vowstar** [comment]
The [v1.1.2](https://github.com/vowstar/kflash.py/releases/tag/v1.1.2) have been removed. It is very strange, I'll try other methods.

**Comment by vowstar** [comment]
I did a speculative fix in https://github.com/vowstar/kflash.py/commit/02bed7310338b08a9a5b465577b513f1f6834e53 without tagging, trying to fix the loop restart, pleas try again.

**Comment by vowstar** [comment]
This is indeed quite strange, I tested a helloworld on my side of the bit_mic without a loop restart, this time I modified the timing of writing the sysctl register.

**Comment by vowstar** [comment]
If this does not work, I will use the board-level reset (Because different PCB implementations are not the same, it may not be reliably on some PCBs).

**Comment by damien-lemoal** [comment]
I tried the current master on the MAIX Bit, MAIX Dock and MAIXDUINO and all worked fine. I get a clean reboot after flashing u-boot.bin. So this look all good for me. Please tag a new release !
Thanks for fixing this !

**Comment by damien-lemoal** [comment]
For completeness, I also just tried the MAIX Go, KD233 dev board and a dan-dock (older MAIX Dock). All good. I get a clean reboot.

**Comment by vowstar** [comment]
Thanks for your help with this debugging, I'm starting to release a new version [v1.1.5](https://github.com/vowstar/kflash.py/releases/tag/v1.1.5).
